[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "src/functions"
  base = "/"

[functions]
  included_files = ["public/data/**"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
