[build]
  command = "npm install && npm run build"
  publish = "."
  functions = "functions"
  base = "/"

[context.production.environment]
  NODE_VERSION = "18"

[context.deploy-preview.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
