[build]
  command = "npm install && npm run build && mkdir -p functions/data && cp -r public/data/* functions/data/ && ls -lR functions && ls -lR /var/task"
  publish = "public"
  functions = "functions"
  base = "/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18"
  NETLIFY = "true"
