[build]
  command = "npm install && npm run build && mkdir -p src/functions && echo 'Copying data...' && rm -rf src/functions/data && cp -rv public/data src/functions/ && echo 'Verifying data copy...' && ls -la src/functions/data"
  publish = "public"
  functions = "functions"
  base = "/"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NODE_VERSION = "18"
  NETLIFY = "true"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
