[build]
  command = "npm install && npm run build && cp version.json public/version.json && mkdir -p public/data && cp -R src/data/* public/data/"
  publish = "public"
  functions = "src/functions"
  base = "/"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  publish = "public"
  targetPort = 3000
  port = 3001

[functions]
  included_files = [
    "public/data/**",
    "src/data/**"
  ]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/search"
  to = "/.netlify/functions/server"
  status = 200
