[build]
  command = """
    npm install && 
    npm run build && 
    rm -rf src/data && 
    mkdir -p src/data && 
    cp -R public/data/* src/data/ && 
    echo "Copied: $(find src/data -type f | wc -l) files"
  """
  publish = "public"
  functions = "src/functions"
  base = "/"

[functions]
  included_files = [
    "public/data/**",
    "src/data/**"
  ]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
