[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Serve static files directly
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# API routes go to the search function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/search"
  status = 200
  force = true

# All other requests serve static files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
