[build]
  command = "npm install && npm run build && rm -rf src/functions/data && mkdir -p src/functions/data && cp -r public/data/. src/functions/data/"
  publish = "public"
  functions = "functions"
  base = "/"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NODE_VERSION = "18"
  NETLIFY = "true"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
