[build]
  command = "npm install && npm run build"
  publish = "public"
  functions = "functions"
  base = "/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18"
  NETLIFY = "true"

[context.deploy-preview.environment]
  NODE_VERSION = "18"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"

[build.edge_handlers]
  directory = "edge-handlers"

[build.processing]
  skip_processing = true

[build.include]
  - "public/data/**"
