[build]
  command = "npm install && npm run build && rm -rf functions/data && cp -r public/data functions/ && ls -R functions/data"
  publish = "public"
  functions = "functions"
  base = "/"
  include = ["public/data/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_VERSION = "18"
  NETLIFY = "true"
